from typing import List, Tuple
from app.schemas.research import (
    BacktestResult,
    BacktestMetrics,
    DefinedExperimentSpec,
    EvidenceLevel,
    LearnReport,
)


class ResearchLearner:
    """
    Deterministic rule-based research interpretation engine.
    Transforms a BacktestResult and DefinedExperimentSpec into an honest,
    transparent LearnReport without LLM calls, external APIs, or live market bias.
    """

    MANDATORY_DISCLAIMER: str = (
        "Deterministic synthetic reference data. Results are illustrative and do not represent "
        "real market performance or live execution. This single simulation run does not establish "
        "statistical significance or robustness."
    )

    SHARPE_DESCRIPTIVE_NOTE: str = (
        "Sharpe ratio is descriptive in this prototype and should not be treated as evidence of statistical significance."
    )

    @classmethod
    def evaluate_evidence_level(cls, metrics: BacktestMetrics) -> EvidenceLevel:
        """
        Determines the mutually exclusive evidence level using the strict priority:
        1. total_trades == 0 -> SYNTHETIC_INSUFFICIENT_DATA
        2. total_trades < 3  -> SYNTHETIC_INSUFFICIENT_DATA
        3. gross_return_pct > 0 and net_return_pct <= 0 -> SYNTHETIC_FRICTION_DOMINATED
        4. net_return_pct <= 0 -> SYNTHETIC_NEGATIVE_EDGE
        5. else -> SYNTHETIC_CANDIDATE_FOR_REAL_DATA
        """
        if metrics.total_trades == 0:
            return EvidenceLevel.SYNTHETIC_INSUFFICIENT_DATA
        elif metrics.total_trades < 3:
            return EvidenceLevel.SYNTHETIC_INSUFFICIENT_DATA
        elif metrics.gross_return_pct > 0 and metrics.net_return_pct <= 0:
            return EvidenceLevel.SYNTHETIC_FRICTION_DOMINATED
        elif metrics.net_return_pct <= 0:
            return EvidenceLevel.SYNTHETIC_NEGATIVE_EDGE
        else:
            return EvidenceLevel.SYNTHETIC_CANDIDATE_FOR_REAL_DATA

    @classmethod
    def synthesize_summary(
        cls,
        spec: DefinedExperimentSpec,
        result: BacktestResult,
        evidence_level: EvidenceLevel,
    ) -> str:
        """
        Generates a concise, high-level summary of what occurred in the simulation.
        """
        metrics = result.metrics
        instrument = spec.market_context.instrument
        timeframe = spec.market_context.timeframe
        trades = metrics.total_trades

        if trades == 0:
            return (
                f"Simulation of {instrument} ({timeframe}) produced 0 executed trades across the reference period. "
                "The defined signal conditions were never satisfied, yielding no empirical data for performance analysis."
            )

        net_str = f"+{metrics.net_return_pct}%" if metrics.net_return_pct >= 0 else f"{metrics.net_return_pct}%"
        gross_str = f"+{metrics.gross_return_pct}%" if metrics.gross_return_pct >= 0 else f"{metrics.gross_return_pct}%"

        if evidence_level == EvidenceLevel.SYNTHETIC_INSUFFICIENT_DATA:
            return (
                f"Simulation of {instrument} ({timeframe}) generated only {trades} trade(s) with net return of {net_str}. "
                "The sample size is insufficient to draw meaningful quantitative conclusions."
            )
        elif evidence_level == EvidenceLevel.SYNTHETIC_FRICTION_DOMINATED:
            return (
                f"Simulation of {instrument} ({timeframe}) generated {trades} trades with a positive gross return of {gross_str}, "
                f"but transaction friction turned net return negative ({net_str})."
            )
        elif evidence_level == EvidenceLevel.SYNTHETIC_NEGATIVE_EDGE:
            return (
                f"Simulation of {instrument} ({timeframe}) generated {trades} trades resulting in a negative net return of {net_str} "
                f"(gross return {gross_str}), indicating an unfavorable simulated expectancy."
            )
        else:
            return (
                f"Simulation of {instrument} ({timeframe}) generated {trades} trades with net return of {net_str} "
                f"(gross return {gross_str}) and a win rate of {metrics.win_rate_pct}%, indicating positive synthetic expectancy."
            )

    @classmethod
    def compile_performance_observations(
        cls,
        metrics: BacktestMetrics,
    ) -> List[str]:
        """
        Synthesizes factual performance observations. Does not fabricate observations if zero trades.
        """
        if metrics.total_trades == 0:
            return [
                "Zero simulated trades were generated by the signal rules during the backtest window.",
                "No trade-level win rate, holding period, or return expectancy could be computed.",
                "Verify whether the entry threshold or regime filters were too restrictive for the reference data.",
            ]

        obs: List[str] = []

        # Sample size observation
        if metrics.total_trades < 3:
            obs.append(
                f"Small sample size alert: Only {metrics.total_trades} trade(s) observed. "
                "Performance metrics carry high variance and cannot establish reliability."
            )
        else:
            obs.append(
                f"Total simulated trades: {metrics.total_trades} ({metrics.winning_trades} wins, {metrics.losing_trades} losses)."
            )

        # Win rate & Profit factor
        obs.append(
            f"Observed win rate is {metrics.win_rate_pct}%, with a profit factor of {metrics.profit_factor}."
        )

        # Average trade return
        avg_ret_sign = "+" if metrics.avg_trade_return_pct >= 0 else ""
        obs.append(
            f"Average net trade return: {avg_ret_sign}{metrics.avg_trade_return_pct}% per round-trip trade."
        )

        # Average holding period
        obs.append(
            f"Average position duration: {metrics.avg_holding_bars} bar(s) between candle t+1 open entry and exit."
        )

        return obs

    @classmethod
    def compile_friction_observation(
        cls,
        metrics: BacktestMetrics,
        cost_assumptions: str,
    ) -> str:
        """
        Examines gross return, net return, and friction drag.
        """
        if metrics.total_trades == 0:
            return (
                f"No transaction friction was incurred because zero trades were executed "
                f"(modeled cost assumption: '{cost_assumptions}')."
            )

        gross_str = f"{metrics.gross_return_pct}%"
        net_str = f"{metrics.net_return_pct}%"
        drag_str = f"{metrics.friction_drag_pct}%"

        if metrics.friction_drag_pct == 0.0:
            return (
                f"Idealized cost condition: Modeled friction drag is 0.0% ({cost_assumptions}). "
                f"Gross return ({gross_str}) and net return ({net_str}) are identical."
            )

        if metrics.gross_return_pct > 0 and metrics.net_return_pct <= 0:
            return (
                f"Friction wipeout: The simulation generated positive gross return of +{gross_str}, "
                f"but transaction friction of -{drag_str} based on '{cost_assumptions}' "
                f"reduced the final net return to {net_str}."
            )

        if metrics.net_return_pct > 0:
            return (
                f"Net return of +{net_str} withstood friction drag of -{drag_str} "
                f"(gross return: +{gross_str}, modeled cost: '{cost_assumptions}')."
            )

        return (
            f"Friction drag contributed -{drag_str} to overall losses "
            f"(gross return: {gross_str}, net return: {net_str}, modeled cost: '{cost_assumptions}')."
        )

    @classmethod
    def compile_risk_observations(
        cls,
        metrics: BacktestMetrics,
    ) -> List[str]:
        """
        Synthesizes risk, drawdown, and descriptive Sharpe observations.
        """
        if metrics.total_trades == 0:
            return [
                "Maximum drawdown was 0.0% as portfolio equity remained at starting capital.",
                cls.SHARPE_DESCRIPTIVE_NOTE,
            ]

        risk_obs: List[str] = []

        # Drawdown observation
        dd_note = f"Maximum simulated portfolio drawdown was {metrics.max_drawdown_pct}% from peak equity."
        if metrics.net_return_pct > 0 and metrics.max_drawdown_pct > metrics.net_return_pct:
            dd_note += " Note: Peak-to-trough drawdown exceeded the final net return."
        risk_obs.append(dd_note)

        # Sharpe ratio observation (purely descriptive)
        if metrics.sharpe_ratio is not None:
            risk_obs.append(
                f"Simulated Sharpe ratio is {metrics.sharpe_ratio}. {cls.SHARPE_DESCRIPTIVE_NOTE}"
            )
        else:
            risk_obs.append(
                f"Sharpe ratio was not computed (requires ≥2 trades with non-zero variance). {cls.SHARPE_DESCRIPTIVE_NOTE}"
            )

        return risk_obs

    @classmethod
    def compile_limitations(
        cls,
        spec: DefinedExperimentSpec,
    ) -> List[str]:
        """
        Mandatory explicit limitations regarding synthetic simulation.
        """
        return [
            cls.MANDATORY_DISCLAIMER,
            "Synthetic data assumes idealized stationary distributions and does not reflect real market liquidity, volume spikes, or regime shifts.",
            "Single-path simulation: Results reflect a single deterministic seed trajectory and do not capture multi-path stochastic variation.",
            f"Cost assumption '{spec.backtest_bounds.cost_assumptions}' is static and does not simulate variable exchange fees, widening spreads during high volatility, or order queue position.",
            "Execution assumed fills at exact open/target/stop prices without intra-bar slippage extremes or market impact.",
        ]

    @classmethod
    def recommend_next_research_steps(
        cls,
        metrics: BacktestMetrics,
        evidence_level: EvidenceLevel,
    ) -> List[str]:
        """
        Formulates valid research questions and investigation avenues.
        Does NOT give trading advice or parameter optimization prescriptions.
        """
        steps: List[str] = []

        if metrics.total_trades == 0:
            steps.append("Examine if the entry condition logic or thresholds are calibrated appropriately for the instrument's volatility range.")
            steps.append("Inspect the timeframe and bar count to determine whether a longer sample window is needed to observe candidate events.")
            steps.append("Formulate a research hypothesis comparing relative percentage drops against historical volatility metrics like ATR.")
            return steps

        # Universal research steps
        steps.append("Validate the hypothesis against actual historical tick or minute data to evaluate real market behavior.")
        steps.append("Conduct parameter sensitivity analysis across adjacent threshold and holding period values to detect curve-fitting.")
        steps.append("Test the strategy across different market regimes (e.g., bull trends, bear regimes, and high-volatility flash crashes).")

        if evidence_level == EvidenceLevel.SYNTHETIC_FRICTION_DOMINATED:
            steps.append("Stress-test transaction costs across different fee schedules and execution venue assumptions.")
            steps.append("Investigate whether multi-day holding periods alter the ratio of gross gains to transaction friction.")
        elif evidence_level == EvidenceLevel.SYNTHETIC_CANDIDATE_FOR_REAL_DATA:
            steps.append("Perform walk-forward out-of-sample testing across distinct historical epochs.")
            steps.append("Test robustness across alternative or non-correlated asset classes to check for generalized edge.")
        elif evidence_level == EvidenceLevel.SYNTHETIC_NEGATIVE_EDGE:
            steps.append("Investigate alternative entry or regime filter hypotheses to determine under what market conditions the pattern fails.")
            steps.append("Analyze whether adverse excursion during trade holding indicates premature exits or adverse momentum continuation.")

        return steps

    @classmethod
    def generate_report(
        cls,
        result: BacktestResult,
        spec: DefinedExperimentSpec,
    ) -> LearnReport:
        """
        Generates a comprehensive, deterministic LearnReport from backtest results and spec.
        """
        evidence_level = cls.evaluate_evidence_level(result.metrics)
        summary = cls.synthesize_summary(spec, result, evidence_level)
        performance_obs = cls.compile_performance_observations(result.metrics)
        friction_obs = cls.compile_friction_observation(
            result.metrics,
            spec.backtest_bounds.cost_assumptions,
        )
        risk_obs = cls.compile_risk_observations(result.metrics)
        limitations = cls.compile_limitations(spec)
        next_steps = cls.recommend_next_research_steps(result.metrics, evidence_level)

        return LearnReport(
            experiment_id=result.experiment_id,
            instrument=result.instrument,
            timeframe=result.timeframe,
            evidence_level=evidence_level,
            summary=summary,
            performance_observations=performance_obs,
            friction_observation=friction_obs,
            risk_observations=risk_obs,
            limitations=limitations,
            next_research_steps=next_steps,
            disclaimer=cls.MANDATORY_DISCLAIMER,
        )
